### PR TITLE
Issue template file

### PR DESCRIPTION
**Pull request by jacobra19**
Added github basic issue template

### CODE REVIEW

**Comment by GabiGrin** [comment]
@jacobra19 it's full of package bumps with versions that do not exist (following the [discord convo](https://discord.com/channels/960219394871533588/1124260541410594867/1156700391803719807))
also, TBH I am not sure this template adds much value.

When debugging something related to Flyde, that's what I'll probably ask:
1. Flyde extension version
2. VSCode version
3. Node version
4. Flyde packages version (in case it's a report regarding direct usage of Flyde's runtime)
5. VSCode dev tools logs (Help > Toggle Developer Tools)
6. The .flyde flow that is causing issues (if applicable)

**Comment by jacobra19** [comment]
Updated

**Comment by GabiGrin** [comment]
Thanks!
I just took a look at [Svelte's template[(https://github.com/sveltejs/svelte/blob/master/.github/ISSUE_TEMPLATE.md) for reference and noticed that the template your suggesting assumes the issue will always be a bug, which is hopefully not true.
Also, the formatting could be improved - see the suggested https://github.com/flydelabs/flyde/blob/b717a561867c20fbf095921159cfc8b0f57f3433/.github/ISSUE_TEMPLATE.md
perhaps headings? 🤔

**Review by GabiGrin — APPROVED** [review]

**Comment by GabiGrin** [comment]
Ended up using Svelte's templates with light modifications. Even fixed a small typo there thanks to it (https://github.com/sveltejs/svelte/pull/10487)

Thanks for the attempt!

**Pull request closed without merging**
